### ISSUE TITLE
 Optional _answers has feedback error

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt-contrib-textInput#58] opened 2015-07-01 09:01 UTC
On develop branch using optional _answers results in incorrect feedback and showCorrectAnswer.

Feedback only shows partly correct when all are correct.

showCorrectAnswer function only looks at answers in _items.

**Comment by moloko** [comment] 2015-07-06 16:14
I think #61 might fix this?

**Comment by danielghost** [comment] 2015-07-15 10:46
#61 does seem to fix this and ABU-869, which is a duplicate of #58.

There are some queries about the implementation of this fix currently though.

**Comment by dancgray** [comment] 2015-07-30 13:48
Can we close this issue now and open another if there are remaining queries about feedback implementation?

**Comment by oliverfoster** [comment] 2015-08-26 10:17
close fixed

**Closed by oliverfoster** 2015-08-26 10:17 UTC
Labels: bug
